CI/CD configuration
rko619619/task_manager pull request #2
Opened 2024-02-03 19:05 UTC by rko619619

1. Add config for CI/CD

2024-02-05 08:14 UTC, Volosh1n approved these changes

2024-02-05 09:08 UTC, ar2em1s requested changes
Good job. Will you add deployment in this MR too?

2024-02-05 09:08 UTC, ar2em1s commented on .github/workflows/rubyonrails.yml
> +        image: postgres:11-alpine
Use newer db image please

2024-02-05 09:08 UTC, ar2em1s commented on .github/workflows/rubyonrails.yml
> +    branches: [ "main" ]
Run CI on every pull request, it should highlight issues earlier

2024-02-06 08:05 UTC, Volosh1n approved these changes

2024-02-07 21:11 UTC, merged